source 'https://rubygems.org'

gem 'middleman', '>= 4.0.0'
gem 'rouge'
gem 'redcarpet'
gem 'middleman-syntax'
gem 'middleman-livereload'
gem 'slim'
gem 'builder'
gem 'middleman-dato', '0.6.0'
gem 'middleman-paginate', '0.1.3'
