source 'https://rubygems.org'

gem 'middleman', '>= 4.0.0'
gem 'rouge'
gem 'redcarpet'
gem 'middleman-syntax'
gem 'middleman-livereload'
gem 'slim'
gem 'builder'
gem 'middleman-dato', path: '/Users/stefanoverna/code/sites/datocms/middleman-dato'
gem 'dato', path: '/Users/stefanoverna/code/sites/datocms/ruby-datocms-client'
gem 'middleman-paginate', path: '/Users/stefanoverna/code/github/middleman-paginate'
